### ISSUE TITLE
6.1.1 Rewards Page - Redesign

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-friends#4]
## MVP
- [x] Add Featured Images to Partners (where Rewards are stored)
- [x] Fix Rewards Links to show UTM source
- [X] Fix Grid so floats are accurate.

**Comment by jimtrue** [comment]
Tested with existing shortcodes and was able to recreate page: https://friends.pods.io/rewards/ need to switch to Archive Layout for 'partners' and change the slug to 'rewards' so the Beaver Themer Layout can use a Posts Module and I can substitute the Reward Details card for each post.

**Comment by jimtrue** [comment]
This page is done. Just needs Review.

**Comment by jimtrue** [comment]
From Scott: rewards links should all add `?utm_source=pods_reward&utm_medium=banner&utm_campaign=pods` to the links

done and fixed grid issue. I'd still like to flip this to a taxonomy filter, but it's not required for launch.

**Comment by jimtrue** [comment]
Ready for Review: https://friends.pods.io/rewards/

**Comment by sc0ttkclark** [comment]
✅

**Comment by jimtrue** [comment]
Sweet, thanks ;)

**Comment by jimtrue** [comment]
Breaking nice to have into a Phase 2 issue #17
