### ISSUE TITLE
6.4 Friends & Partner Page Redesign

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-friends#5]
- [x] Populate Friends, identify by Group [Automatic from Donations?]
- [x] Add fields to `Friends` to allow additional functionality
- [x] Show on Front-end?
- [x] What to display, personal name or company name, twitter, etc.
- [x] Also display Partners 
- [x] Fix image issue on Pillar & Gold
- [x] Center Image (or use Image) from Reward Partners so Featured Image isn't required at Friend level side.
- [x] Add utm_source, etc. to Friends & Partners Links

**Comment by jimtrue** [comment]
Page is mostly done, needs some minor tweaks: https://friends.pods.io/friends-and-partners/

**Comment by jimtrue** [comment]
our partners should use `?utm_source=pods_partner&utm_medium=banner&utm_campaign=pods`, the other links/images on the left should use `?utm_source=pods_sponsor&utm_medium=link&utm_campaign=pods`

**Comment by jimtrue** [comment]
Adding source links above, fixed image issues on Pillar/Gold and moved all style configurations out of the Pods Templates and into Custom CSS for the website.

**Comment by jimtrue** [comment]
Ready for your Review @sc0ttkclark

**Comment by sc0ttkclark** [comment]
✅
